#ifndef CAMERA_CALIBRATION_CALIBRATION_H
#define CAMERA_CALIBRATION_CALIBRATION_H

enum class Pattern {
    CHESSBOARD,
    CIRCLES,
    CIRCLES_ASYMMETRIC
};

enum class Model {
    DEFAULT,
    FISHEYE
};

#endif // CAMERA_CALIBRATION_CALIBRATION_H
